config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users

  get 'welcome', to: "welcome#index"
  resources :rooms do
    resources :messages
  end

  resources :private_chats, only: %i[show]

  namespace :manager do
    root 'home#index'
    resources :companies
  end

  namespace :account do
    root 'home#index'
    get 'search', to: 'home#search'
    resources :users, only: %i[edit update show destroy]
    resources :products do
      get 'desactive', on: :member
      get 'active', on: :member
      get 'wish_list', on: :member
    end
  end

  resources :documents, only: %i[show]

  namespace :advertise do
    resources :products  do
      member do
        get :join, to: 'products#join'
        get :leave, to: 'products#leave'
      end
    end
  end

  # get 'rooms/index'
  # resources :users
  # root 'rooms#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_alert.html.erb
<div class="alert-error-minutes">
  <div class="message-error-minutes">
    <div class="icon-error-minutes">
      <%= image_tag('icon-error.svg')%>
    </div>
    <div class="text-error-minutes">
      <p>Complete seu cadastro ter acesso total a plataforma</p>
    </div>
  </div>
</div>

app/views/shared/_filter.html.erb
<div class="dropdown">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Dropdown link
  </a>

  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="#">Action</a></li>
    <li><a class="dropdown-item" href="#">Another action</a></li>
    <li><a class="dropdown-item" href="#">Something else here</a></li>
  </ul>
</div>

app/views/shared/_layout.html.erb
<div class="navbar-top">
  <div class="search-bar">
    <div class="input-group mb-3">
      <%= form_with url: account_search_path, class: 'search-form', method: :get, local: true do %>
        <%= text_field_tag :query,nil,  class: 'form-control', placeholder: 'Pesquisar' %>
        <div class="input-group-append">
          <%= image_submit_tag('search.svg', id: 'submit-search') %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/shared/_sidebar_admin.html.erb
<div class="navbar-side">
	<%= link_to 'Cadastrar empresa', new_manager_company_path, class: "btn-sidebar-#{current_page?(new_manager_company_path)}" %>
	<% if admin_signed_in?  %>
  	<%= button_to "Sair", destroy_admin_session_path, method: :delete, class: "btn-sidebar-false" %>
	<% end %>
</div>

app/views/shared/_sidebar_user.html.erb
<div class="offcanvas offcanvas-start width-canvas-left-side" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions" aria-labelledby="offcanvasWithBothOptionsLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel"> Olá <%= current_user.name %> </h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
	<div class="navbar-side">
		<%= link_to "Home", account_root_path, class: "btn-sidebar-#{current_page?(account_root_path)}" %>
		
		<a class="btn btn-sidebar-false" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
			Ordenar
		</a>
		<div class="collapse" id="collapseExample">
			<div class="card card-body">
				<%= link_to 'Mais recentes', account_root_path(order: :desc), class: "btn-sidebar-false" %>
				<%= link_to 'Mais antigos', account_root_path(order: :asc), class: "btn-sidebar-false" %>
				<%= link_to 'Maior preço', account_root_path(price: :desc), class: "btn-sidebar-false" %>
				<%= link_to 'Menor preço', account_root_path(price: :asc), class: "btn-sidebar-false" %>
			</div>
		</div>


		<%= link_to "Cadastrar anuncio", new_account_product_path, class: "btn-sidebar-#{current_page?(new_account_product_path)}", id: "create-adv-#{current_user.active?}" %>

		<a class="btn btn-sidebar-false" data-bs-toggle="collapse" href="#collapseHistory" role="button" aria-expanded="false" aria-controls="collapseHistory">
			Meu historico
		</a>
		<div class="collapse" id="collapseHistory">
			<div class="card card-body">
				<%= link_to "Anuncios", account_products_path, class: "btn-sidebar-#{current_page?(account_products_path)}",  id: "my-adv-#{current_user.active?}"%>
				<%= link_to "Participações", wish_list_account_product_path(current_user), class: "btn-sidebar-#{current_page?(wish_list_account_product_path(current_user))}", id: "my-list-#{current_user.active?}" %>
			</div>
		</div>

		<% if current_user.active? %>
			<%= link_to image_tag('profile.svg'),  account_user_path(current_user), class: "btn-sidebar-#{current_page?(account_user_path(current_user))} profile-icon" %> 
		<% else %>
			<%= link_to image_tag('profile.svg'), edit_account_user_path(current_user), class: 'btn-sidebar-false profile-icon' %>
		<% end %>

		<%= link_to image_tag('rooms.svg', width: 38), rooms_path, class: "btn-sidebar-#{current_page?(rooms_path)}", id: "create-adv-#{current_user.active?}" %>
		
		<% if user_signed_in?  %>
			<%= button_to "Sair", destroy_user_session_path, method: :delete, class: "btn-sidebar-false" %>
		<% end %>
	</div>
</div>


<%= render 'shared/alert' %>