config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users

  get 'welcome', to: "welcome#index"
  resources :rooms do
    resources :messages
  end

  resources :private_chats, only: %i[show]

  namespace :manager do
    root 'home#index'
    resources :companies
  end

  namespace :account do
    root 'home#index'
    get 'search', to: 'home#search'
    resources :users, only: %i[edit update show destroy]
    resources :products do
      get 'desactive', on: :member
      get 'active', on: :member
      get 'wish_list', on: :member
    end
  end

  resources :documents, only: %i[show]

  namespace :advertise do
    resources :products  do
      member do
        get :join, to: 'products#join'
        get :leave, to: 'products#leave'
      end
    end
  end

  # get 'rooms/index'
  # resources :users
  # root 'rooms#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :agrees
  has_many :joins, through: :agrees, source: :user
  belongs_to :user
  has_many_attached :images, dependent: :destroy

  enum status: { active: 0 , desactive: 1 }
end

app/controllers/account/products_controller.rb
require 'csv'
module Account
  class ProductsController < AccountController
    before_action :authenticate_user!
    before_action :user_active!, only: [:new, :create, :edit, :update, :desactive, :active, :wish_list]

    def index
      @list_product = Product.where(user_id: current_user)
        .order(created_at: :desc)
        .page(params[:page])
        .per(5)
      @advertise_products = @list_product.map do |product|
        ProductPresenter.new(product, current_user)
      end
    end

    def new
      @product = Product.new
    end

    def create
      Advertise::CreateProductService.new(params_permitted, current_user).execute
      # redirect_to account_products_path
    end

    def edit
      @product = Product.find(params[:id])
    end

    def update
      product = Product.find(params[:id])
      Advertise::EditProductService.new(params_permitted, product).execute
    end


    def desactive
      advertise = current_user.products.find(params[:id])
      advertise.desactive!

      redirect_to account_products_path(page: params[:page])
    end

    def active
      advertise = current_user.products.find(params[:id])
      advertise.active!

      redirect_to account_products_path(page: params[:page])
    end

    def wish_list
      @products = current_user.participate_list
      .order(created_at: :desc)
      .page(params[:page])
      .per(4)

      @advertise_products = @products.map do |product|
        ProductPresenter.new(product, current_user)
      end
    end
    
    private

    def params_permitted
      params.require(:product).permit(:amount, :price, :title, :body, images: [])
      # params[:product][:images] = params[:product][:image1], params[:product][:image2]
      # params[:product].delete(:image1)
      # params[:product].delete(:image2)
      # params[:product].delete(:authenticity_token)
      # params
    end

    def user_active!
      if current_user.inactive?
        redirect_to account_root_path, alert: "Solicitação nao permitida"
      end
    end

  end
end

app/controllers/advertise/products_controller.rb
module Advertise
  class ProductsController < ApplicationController

    before_action :authenticate_user!
    before_action :check_user

    def show
      adv = Product.find(params[:id])
      @product = ProductPresenter.new(adv, current_user)
    rescue ActiveRecord::RecordNotFound
      redirect_to account_products_path, flash[:alert] = "Houve um erro, produto nao encontrado"
    end

    def join
      product = Product.find(params[:id])
      Advertise::JoinListProductService.new(product, current_user).execute
      redirect_to advertise_product_path(product)
    end

    def leave
      product = Product.find(params[:id])
      Advertise::LeaveListProductService.new(product, current_user).execute
      redirect_to advertise_product_path(product)
    end

    private

    def check_user
      if current_user.inactive?
        redirect_to account_root_path, alert: "Acesso negado"
      end
    end
  end
end

app/views/advertise/products/_description_product.html.erb
<h1 class="title-advertise">
  <%= @product.title  %>
</h1>
<h2 class="price-advertise">
  Valor <%= number_to_currency(@product.price) %>
</h2>

app/views/advertise/products/_detail_product.html.erb
<div class="detail-product">
  <h2>Descrição do produto</h2>
  <p>
    <%= @product.description %>
  </p>
</div>

app/views/advertise/products/_join.erb
<div class="container stretch">
  <div class="form-register item-interest">
    <div class="side-left interest">
      <%= "#{@product.interests} Interessados"  %>
    </div>
  </div>

  <div class="item-interest">
    <div class="side-right">
      <% if @product.owner? %>
        <%= image_tag('join.svg', size: "130") %>
        <div class="interest">
            Aguarde, a lista não esta completa
        </div>
      <% elsif @product.already_join? %>
        <%= link_to image_tag('joined.svg', size: "130"), leave_advertise_product_path(@product) %>
        <div class="interest">
            Voce está nessa lista
        </div>
      <% else !@product.already_join? %>
        <%= link_to image_tag('join.svg', size: "130"), join_advertise_product_path(@product) %>
        <div class="interest">
            Participar da lista
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/advertise/products/_join.html.erb
  <div class="item-interest">
    <div class="side-left interest">
      <%= "#{@product.interests} Interessados"  %>
    </div>
  </div>

  <div class="item-interest">
    <div>
      <% if @product.owner? %>
        <%= image_tag('join.svg', size: "130") %>
        <div class="interest">
            Aguarde, a lista não esta completa
        </div>
      <% elsif @product.already_join? %>
        <%= link_to image_tag('joined.svg', size: "130"), leave_advertise_product_path(@product)%>
        <div class="interest">
            Voce está nessa lista
        </div>
      <% else !@product.already_join? %>
        <%= link_to image_tag('join.svg', size: "130"), join_advertise_product_path(@product) %>
        <div class="interest">
            Participar da lista
        </div>
      <% end %>
    </div>
  </div>

app/views/advertise/products/_product_images.html.erb
<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">

  <div class="carousel-indicators">
    <% if @product.image? %>
      <%  @product.images.each_with_index do |image, index| %>
        <%= button_tag '', class: "active",  "data-bs-target"=> "#carouselExampleDark" ,  "data-bs-slide-to" => "#{index}", "aria-label"=>"Slide #{index+1}" %>
      <% end %>
    <% end %>
  </div>

  <div class="carousel-inner">
    <%  @product.images.each_with_index do |image, index| %>
      <div class="carousel-item <%= index==0 ? 'active' : '' %>", data-bs-interval="10000" >
        <%= image_tag(image.representation(resize_and_pad: [360, 360])) %>
      </div>
    <% end %>
  </div>

  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>

</div>

app/views/advertise/products/banana.html.erb
<%= render "shared/layout" %>
<div class='content-middle-body'>
  <div>
    <button class="btn" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions"> <%= image_tag('menu.svg', width: "50px", height: '38px') %> </button>
    <%= render "shared/sidebar_user" %>
  </div>

  <div class="wrapper">
    <div class="box-auth ">
      <div class="box-wrapper advertise-box">
        <div><%= link_to "Voltar á lista", :back %></div>

        <div class="content-top">

          <div class="container stretch">
            <div class="form-register item advertise-image-text">
              <div class="side-left">
                <% if @product.image? %>
                  <%= render 'product_images', locals: {product: @product} %>
                <% else %>
                  <%= (image_tag('sem-foto.jpg', width: "115px")) %>
                <% end %>
              </div>
            </div>

            <div class="item">
              <div class="side-right">
                <%= render 'description_product', locals: {product: @product} %>
              </div>
            </div>
          </div>

          <div>
            <div >
              <%= render 'join', locals: {product: @product} %>
            </div>
          </div>
          
        </div>

        <div class="content-bottom">
          <div class="wrapper-bottom">
            <%= render 'detail_product', locals: {product: @product} %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/advertise/products/show.html.erb
<%= render "shared/layout" %>
<div class='content-middle-body'>
  <div>
    <button class="btn" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions"> <%= image_tag('menu.svg', width: "50px", height: '38px') %> </button>
    <%= render "shared/sidebar_user" %>
  </div>

  <div class="wrapper-advertise">
    <div class="box-auth-advertise">
      <div class="box-wrapper-advertise">
        <div class="container-advertise">
          <div class="content-top">
            <div class="side-left">
              <% if @product.image? %>
                <%= render 'product_images', locals: {product: @product} %>
              <% else %>
                <%= (image_tag('sem-foto.jpg', width: "115px")) %>
              <% end %>
            </div>

            <div class="side-right">
              <%= render 'description_product', locals: {product: @product} %>
            </div>
          </div>

            <div class="content-middle">
              <%= render 'join', locals: {product: @product} %>
            </div>

          <div class="content-bottom">
            <%= render 'detail_product', locals: {product: @product} %>
          </div>


        </div>
      </div>
    </div>
  </div>
</div>